In [ ]:
import numpy as np

predictions = np.array([[0.2, 0.3, 0.1, 0.1, 0.3],
                        [0.8, 0.1, 0.05, 0.02, 0.03],
                        [0.1, 0.2, 0.6, 0.05, 0.05],
                        [0.2, 0.42, 0, 0, 0.38]]
                       )

predicted_classes = np.argmax(predictions, axis=1)
predicted_classes

array([1, 0, 2, 1])

In [ ]:
confidence_scores = np.max(predictions, axis=1)
confidence_scores

array([0.3 , 0.8 , 0.6 , 0.42])

In [ ]:
true_labels = np.array([4,0,2,4])
low_confidence_threshold = 0.4
high_confidence_threshold = 0.8

low_confidence_samples = confidence_scores < low_confidence_threshold
high_confidence_samples = confidence_scores > high_confidence_threshold

incorrectly_classified_samples = predicted_classes != true_labels

In [ ]:
def get_low_confidence_samples(predictions,low_confidence_threshold = 0.4):
    n = len(predictions)
    low = []
    for i in range(n):
        p = sorted(predictions[i])
        if p[-1]<low_confidence_threshold or p[-1]-p[-2]<0.05:
            low.append(True)
        else:
            low.append(False)
    return np.array(low)

def low_high_incorrect(true_labels, predictions,low_confidence_threshold = 0.4,high_confidence_threshold = 0.7):
    predicted_classes = np.argmax(predictions, axis=1)
    confidence_scores = np.max(predictions, axis=1)
    low_confidence_samples = get_low_confidence_samples(predictions)
    high_confidence_samples = confidence_scores >= high_confidence_threshold
    incorrectly_classified_samples = predicted_classes != true_labels
    return(low_confidence_samples, high_confidence_samples, incorrectly_classified_samples)

In [ ]:
low_confidence_samples = get_low_confidence_samples(predictions)

In [ ]:
low_confidence_samples, high_confidence_samples, incorrectly_classified_samples

(array([ True, False, False,  True]),
 array([False, False, False, False]),
 array([ True, False, False,  True]))

In [ ]:
print(low_high_incorrect(true_labels, predictions))

(array([ True, False, False,  True]), array([False,  True, False, False]), array([ True, False, False,  True]))
